<a href="https://colab.research.google.com/github/Jaeljane/Secondary-school-data-analysis/blob/main/Secondary_School_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
 #import standard library 

#data analysis
import pandas as pd
import numpy as np


#plotting
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px
# Read csv
df=pd.read_csv("/content/Secpndary School Clear Data.csv")

In [116]:
# read top rows
df.head()

     Region  ... Total number of beds
0  Region 1  ...                 61.0
1  Region 1  ...                430.0
2  Region 1  ...                215.0
3  Region 1  ...                  0.0
4  Region 1  ...                  0.0

[5 rows x 89 columns]

In [117]:
# print rows and columns 
df.shape

(1445, 89)

In [118]:
#summary of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 89 columns):
 #   Column                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                             --------------  -----
 0   Region                                                                                                                             1445 non-null   object
 1   Name of County                                                                                                                     1445 non-null   object
 2   Name of Sub- County                                                                                                                1445 non-null   object
 3   Name of School                                                                                                                     1445 non-null   object
 4   School Code (MoE)                                                                                                                  1383 non-null   object
 5   School's P.O. Box number                                                                                                           1440 non-null   object
 6   What is the school category                                                                                                        1444 non-null   object
 7   What is the gender of the students?                                                                                                1445 non-null   object
 8   What form of accommodation does the school operate?                                                                                1445 non-null   object
 9   Type of school                                                                                                                     1445 non-null   object
 10  Location of school                                                                                                                 1441 non-null   object
 11  Did the school receive any funding in the year 2017 or 2018?                                                                       1334 non-null   object
 12  Total income for 2018:                                                                                                             1127 non-null   float64
 13  Total income for 2017:                                                                                                             1126 non-null   float64
 14  How many KCSE candidates did the school have in 2018?                                                                              1438 non-null   float64
 15  What was the overall school mean score in 2018?                                                                                    1440 non-null   float64
 16  What was MATHEMATICS  mean score in 2018?                                                                                          1439 non-null   float64
 17  What was the ENGLISH  mean score in 2018?                                                                                          1439 non-null   float64
 18  What was PHYSICS  mean score in 2018?                                                                                              1434 non-null   float64
 19  What was CHEMISTRY  mean score in 2018?                                                                                            1439 non-null   float64
 20  What was BIOLOGY  mean score in 2018?                                                                                              1439 non-null   float64
 21  How many KCSE candidates did the school have in 2017?                                                                              1439 non-null   float64
 22  What was the overall school mean score in 2017?                                                                                    1439 non-null   float64
 23  What was MATHEMATICS  mean score in 2017?                                                                                          1438 non-null   float64
 24  What was the ENGLISH  mean score in 2017?                                                                                          1438 non-null   float64
 25  What was PHYSICS  mean score in 2017?                                                                                              1433 non-null   float64
 26  What was CHEMISTRY  mean score in 2017?                                                                                            1438 non-null   float64
 27  What was BIOLOGY mean score in 2017?                                                                                               1438 non-null   float64
 28  How many classes did the school have in 2018?                                                                                      1440 non-null   float64
 29  How many classes did the school have in 2019?                                                                                      1440 non-null   float64
 30  Number of boys in Special Needs school                                                                                             126 non-null    float64
 31  Number of girls in Special Needs school                                                                                            127 non-null    float64
 32  Number of students who are visually impaired                                                                                       127 non-null    float64
 33  Number of students who have a hearing impairment                                                                                   126 non-null    float64
 34  Number of students who are physically challenged                                                                                   127 non-null    float64
 35  Number of students who are intellectually challenged                                                                               126 non-null    float64
 36  How many classrooms are there in school?                                                                                           1445 non-null   int64
 37  Does the school have science laboratories?                                                                                         1445 non-null   int64
 38  How many science laboratories are there?                                                                                           1445 non-null   int64
 39  Does the school have Dormitories?                                                                                                  1444 non-null   object
 40  Does the school have Smart Classrooms                                                                                              1444 non-null   object
 41  Does the school have ICT laboratories / Room?                                                                                      1444 non-null   object
 42  Does the school have a library?                                                                                                    1444 non-null   object
 43  What is the general condition of repair of the classrooms?                                                                         1443 non-null   object
 44  Does the school conduct classes in open air or under trees?                                                                        1444 non-null   object
 45  Does the school have toilets for students?                                                                                         1444 non-null   object
 46  Are the student toilets for girls separate from the ones for the boys?                                                             981 non-null    object
 47  What kind of toilets does the school have?                                                                                         1443 non-null   object
 48  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (Bathing areas)              1219 non-null   object
 49  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM materials (e.g. pads))  1219 non-null   object
 50  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM education)              1219 non-null   object
 51  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (None)                       1218 non-null   object
 52  Is the school connected to KLPC electricity?                                                                                       1444 non-null   object
 53  What kind of internet connection does the school have? (Fiber/structured cabling)                                                  1445 non-null   object
 54  What kind of internet connection does the school have? (Wireless Broadband/modem)                                                  1445 non-null   object
 55  What kind of internet connection does the school have? (Mobile phones)                                                             1445 non-null   object
 56  What kind of internet connection does the school have? (None)                                                                      1444 non-null   object
 57  Is noise from the surrounding environment a problem with the school?                                                               1444 non-null   object
 58  Are there some health & safety challenges that may arise as a result of the infrastructural development in your schools?           1444 non-null   object
 59  Is the community prone to insecurity challenges?                                                                                   1444 non-null   object
 60  Does the region experience any inter/intra community conflicts or attacks?                                                         1444 non-null   object
 61  Total Number of Teachers                                                                                                           1440 non-null   float64
 62  Total number of TSC Teachers                                                                                                       1440 non-null   float64
 63  Total number of BOM/PTA teachers                                                                                                   1440 non-null   float64
 64  Total Number of Nonteaching staff                                                                                                  1440 non-null   float64
 65  Total Number of regular  staff                                                                                                     1439 non-null   float64
 66  Total number of BOM/PTA staff                                                                                                      1439 non-null   float64
 67  Total Number of Laboratory Technicians                                                                                             1440 non-null   float64
 68  Total Number of Security staff                                                                                                     1439 non-null   float64
 69  Total School enrolment                                                                                                             1445 non-null   int64
 70  Total enrolment in form 1 in 2018 and 2019                                                                                         1445 non-null   int64
 71  Total School enrolment in 2018 and 2019                                                                                            1445 non-null   int64
 72  Enrolment in form 1 in the last 2 years                                                                                            1439 non-null   float64
 73  Total girls enrolment                                                                                                              1443 non-null   float64
 74  Total boys enrolment                                                                                                               1443 non-null   float64
 75  Girls' enrolment Level of enrolment                                                                                                1440 non-null   float64
 76  Adequacy of classrooms                                                                                                             1438 non-null   float64
 77  Over-crowded classrooms                                                                                                            1438 non-null   float64
 78  Total number of classrooms available                                                                                               1444 non-null   float64
 79  Total Form 2 enrollment                                                                                                            1444 non-null   float64
 80  Number of Form 2 streams                                                                                                           1444 non-null   float64
 81  Average Form 2 students                                                                                                            1442 non-null   float64
 82  Adequacy of laboratories                                                                                                           1439 non-null   float64
 83  Total lab floor area                                                                                                               1441 non-null   float64
 84  Total enrolment of boarders                                                                                                        1444 non-null   float64
 85  Total Dormitory Floor area                                                                                                         1443 non-null   float64
 86  Temporary Dormitory                                                                                                                1444 non-null   float64
 87  Inadequate and overcrowded  dormitories                                                                                            1440 non-null   float64
 88  Total number of beds                                                                                                               1439 non-null   float64
dtypes: float64(49), int64(6), object(34)
memory usage: 1004.9+ KB

In [119]:
# name of the columns 
df.columns.values

array(['Region', 'Name of County', 'Name of Sub- County',
       'Name of School', 'School Code (MoE)', "School's P.O. Box number",
       'What is the school category',
       'What is the gender of the students?',
       'What form of accommodation does the school operate?',
       'Type of school', 'Location of school',
       'Did the school receive any funding in the year 2017 or 2018?',
       'Total income for 2018: ', 'Total income for 2017: ',
       'How many KCSE candidates did the school have in 2018?',
       'What was the overall school mean score in 2018?',
       'What was MATHEMATICS  mean score in 2018?',
       'What was the ENGLISH  mean score in 2018?',
       'What was PHYSICS  mean score in 2018?',
       'What was CHEMISTRY  mean score in 2018?',
       'What was BIOLOGY  mean score in 2018?',
       'How many KCSE candidates did the school have in 2017?',
       'What was the overall school mean score in 2017?',
       'What was MATHEMATICS  mean score in 2017?',
       'What was the ENGLISH  mean score in 2017?',
       'What was PHYSICS  mean score in 2017?',
       'What was CHEMISTRY  mean score in 2017?',
       'What was BIOLOGY mean score in 2017?',
       'How many classes did the school have in 2018?',
       'How many classes did the school have in 2019?',
       'Number of boys in Special Needs school',
       'Number of girls in Special Needs school',
       'Number of students who are visually impaired  ',
       'Number of students who have a hearing impairment',
       'Number of students who are physically challenged',
       'Number of students who are intellectually challenged',
       'How many classrooms are there in school?',
       'Does the school have science laboratories?',
       'How many science laboratories are there?',
       'Does the school have Dormitories?',
       'Does the school have Smart Classrooms',
       'Does the school have ICT laboratories / Room?',
       'Does the school have a library?',
       'What is the general condition of repair of the classrooms?',
       'Does the school conduct classes in open air or under trees?',
       'Does the school have toilets for students?    ',
       'Are the student toilets for girls separate from the ones for the boys?  ',
       'What kind of toilets does the school have?',
       'Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (Bathing areas)',
       'Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM materials (e.g. pads))',
       'Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM education)',
       'Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (None)',
       'Is the school connected to KLPC electricity?',
       'What kind of internet connection does the school have? (Fiber/structured cabling)',
       'What kind of internet connection does the school have? (Wireless Broadband/modem)',
       'What kind of internet connection does the school have? (Mobile phones)',
       'What kind of internet connection does the school have? (None)',
       'Is noise from the surrounding environment a problem with the school?',
       'Are there some health & safety challenges that may arise as a result of the infrastructural development in your schools?  ',
       'Is the community prone to insecurity challenges?  ',
       'Does the region experience any inter/intra community conflicts or attacks? ',
       'Total Number of Teachers', 'Total number of TSC Teachers',
       'Total number of BOM/PTA teachers',
       'Total Number of Nonteaching staff',
       'Total Number of regular  staff', 'Total number of BOM/PTA staff',
       'Total Number of Laboratory Technicians',
       'Total Number of Security staff', 'Total School enrolment',
       'Total enrolment in form 1 in 2018 and 2019',
       'Total School enrolment in 2018 and 2019',
       'Enrolment in form 1 in the last 2 years', 'Total girls enrolment',
       'Total boys enrolment', "Girls' enrolment Level of enrolment",
       'Adequacy of classrooms ', 'Over-crowded classrooms ',
       'Total number of classrooms available', 'Total Form 2 enrollment',
       'Number of Form 2 streams', 'Average Form 2 students',
       'Adequacy of laboratories', 'Total lab floor area',
       'Total enrolment of boarders', 'Total Dormitory Floor area',
       'Temporary Dormitory ', 'Inadequate and overcrowded  dormitories ',
       'Total number of beds'], dtype=object)

In [120]:
# Data types of columns
df.dtypes

Region                                       object
Name of County                               object
Name of Sub- County                          object
Name of School                               object
School Code (MoE)                            object
                                             ...
Total enrolment of boarders                 float64
Total Dormitory Floor area                  float64
Temporary Dormitory                         float64
Inadequate and overcrowded  dormitories     float64
Total number of beds                        float64
Length: 89, dtype: object

In [121]:
#check null value 
df.isnull().sum()

Region                                       0
Name of County                               0
Name of Sub- County                          0
Name of School                               0
School Code (MoE)                           62
                                            ..
Total enrolment of boarders                  1
Total Dormitory Floor area                   2
Temporary Dormitory                          1
Inadequate and overcrowded  dormitories      5
Total number of beds                         6
Length: 89, dtype: int64

In [122]:
#summary of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 89 columns):
 #   Column                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                             --------------  -----
 0   Region                                                                                                                             1445 non-null   object
 1   Name of County                                                                                                                     1445 non-null   object
 2   Name of Sub- County                                                                                                                1445 non-null   object
 3   Name of School                                                                                                                     1445 non-null   object
 4   School Code (MoE)                                                                                                                  1383 non-null   object
 5   School's P.O. Box number                                                                                                           1440 non-null   object
 6   What is the school category                                                                                                        1444 non-null   object
 7   What is the gender of the students?                                                                                                1445 non-null   object
 8   What form of accommodation does the school operate?                                                                                1445 non-null   object
 9   Type of school                                                                                                                     1445 non-null   object
 10  Location of school                                                                                                                 1441 non-null   object
 11  Did the school receive any funding in the year 2017 or 2018?                                                                       1334 non-null   object
 12  Total income for 2018:                                                                                                             1127 non-null   float64
 13  Total income for 2017:                                                                                                             1126 non-null   float64
 14  How many KCSE candidates did the school have in 2018?                                                                              1438 non-null   float64
 15  What was the overall school mean score in 2018?                                                                                    1440 non-null   float64
 16  What was MATHEMATICS  mean score in 2018?                                                                                          1439 non-null   float64
 17  What was the ENGLISH  mean score in 2018?                                                                                          1439 non-null   float64
 18  What was PHYSICS  mean score in 2018?                                                                                              1434 non-null   float64
 19  What was CHEMISTRY  mean score in 2018?                                                                                            1439 non-null   float64
 20  What was BIOLOGY  mean score in 2018?                                                                                              1439 non-null   float64
 21  How many KCSE candidates did the school have in 2017?                                                                              1439 non-null   float64
 22  What was the overall school mean score in 2017?                                                                                    1439 non-null   float64
 23  What was MATHEMATICS  mean score in 2017?                                                                                          1438 non-null   float64
 24  What was the ENGLISH  mean score in 2017?                                                                                          1438 non-null   float64
 25  What was PHYSICS  mean score in 2017?                                                                                              1433 non-null   float64
 26  What was CHEMISTRY  mean score in 2017?                                                                                            1438 non-null   float64
 27  What was BIOLOGY mean score in 2017?                                                                                               1438 non-null   float64
 28  How many classes did the school have in 2018?                                                                                      1440 non-null   float64
 29  How many classes did the school have in 2019?                                                                                      1440 non-null   float64
 30  Number of boys in Special Needs school                                                                                             126 non-null    float64
 31  Number of girls in Special Needs school                                                                                            127 non-null    float64
 32  Number of students who are visually impaired                                                                                       127 non-null    float64
 33  Number of students who have a hearing impairment                                                                                   126 non-null    float64
 34  Number of students who are physically challenged                                                                                   127 non-null    float64
 35  Number of students who are intellectually challenged                                                                               126 non-null    float64
 36  How many classrooms are there in school?                                                                                           1445 non-null   int64
 37  Does the school have science laboratories?                                                                                         1445 non-null   int64
 38  How many science laboratories are there?                                                                                           1445 non-null   int64
 39  Does the school have Dormitories?                                                                                                  1444 non-null   object
 40  Does the school have Smart Classrooms                                                                                              1444 non-null   object
 41  Does the school have ICT laboratories / Room?                                                                                      1444 non-null   object
 42  Does the school have a library?                                                                                                    1444 non-null   object
 43  What is the general condition of repair of the classrooms?                                                                         1443 non-null   object
 44  Does the school conduct classes in open air or under trees?                                                                        1444 non-null   object
 45  Does the school have toilets for students?                                                                                         1444 non-null   object
 46  Are the student toilets for girls separate from the ones for the boys?                                                             981 non-null    object
 47  What kind of toilets does the school have?                                                                                         1443 non-null   object
 48  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (Bathing areas)              1219 non-null   object
 49  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM materials (e.g. pads))  1219 non-null   object
 50  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM education)              1219 non-null   object
 51  Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (None)                       1218 non-null   object
 52  Is the school connected to KLPC electricity?                                                                                       1444 non-null   object
 53  What kind of internet connection does the school have? (Fiber/structured cabling)                                                  1445 non-null   object
 54  What kind of internet connection does the school have? (Wireless Broadband/modem)                                                  1445 non-null   object
 55  What kind of internet connection does the school have? (Mobile phones)                                                             1445 non-null   object
 56  What kind of internet connection does the school have? (None)                                                                      1444 non-null   object
 57  Is noise from the surrounding environment a problem with the school?                                                               1444 non-null   object
 58  Are there some health & safety challenges that may arise as a result of the infrastructural development in your schools?           1444 non-null   object
 59  Is the community prone to insecurity challenges?                                                                                   1444 non-null   object
 60  Does the region experience any inter/intra community conflicts or attacks?                                                         1444 non-null   object
 61  Total Number of Teachers                                                                                                           1440 non-null   float64
 62  Total number of TSC Teachers                                                                                                       1440 non-null   float64
 63  Total number of BOM/PTA teachers                                                                                                   1440 non-null   float64
 64  Total Number of Nonteaching staff                                                                                                  1440 non-null   float64
 65  Total Number of regular  staff                                                                                                     1439 non-null   float64
 66  Total number of BOM/PTA staff                                                                                                      1439 non-null   float64
 67  Total Number of Laboratory Technicians                                                                                             1440 non-null   float64
 68  Total Number of Security staff                                                                                                     1439 non-null   float64
 69  Total School enrolment                                                                                                             1445 non-null   int64
 70  Total enrolment in form 1 in 2018 and 2019                                                                                         1445 non-null   int64
 71  Total School enrolment in 2018 and 2019                                                                                            1445 non-null   int64
 72  Enrolment in form 1 in the last 2 years                                                                                            1439 non-null   float64
 73  Total girls enrolment                                                                                                              1443 non-null   float64
 74  Total boys enrolment                                                                                                               1443 non-null   float64
 75  Girls' enrolment Level of enrolment                                                                                                1440 non-null   float64
 76  Adequacy of classrooms                                                                                                             1438 non-null   float64
 77  Over-crowded classrooms                                                                                                            1438 non-null   float64
 78  Total number of classrooms available                                                                                               1444 non-null   float64
 79  Total Form 2 enrollment                                                                                                            1444 non-null   float64
 80  Number of Form 2 streams                                                                                                           1444 non-null   float64
 81  Average Form 2 students                                                                                                            1442 non-null   float64
 82  Adequacy of laboratories                                                                                                           1439 non-null   float64
 83  Total lab floor area                                                                                                               1441 non-null   float64
 84  Total enrolment of boarders                                                                                                        1444 non-null   float64
 85  Total Dormitory Floor area                                                                                                         1443 non-null   float64
 86  Temporary Dormitory                                                                                                                1444 non-null   float64
 87  Inadequate and overcrowded  dormitories                                                                                            1440 non-null   float64
 88  Total number of beds                                                                                                               1439 non-null   float64
dtypes: float64(49), int64(6), object(34)
memory usage: 1004.9+ KB

In [123]:
# drop unique identifier
df.drop(df.columns[[3, 4, 5]], axis=1, inplace=True)
df.head()

     Region  ... Total number of beds
0  Region 1  ...                 61.0
1  Region 1  ...                430.0
2  Region 1  ...                215.0
3  Region 1  ...                  0.0
4  Region 1  ...                  0.0

[5 rows x 86 columns]

In [124]:
#missing values as a percent of observations
df.shape

(1445, 86)

In [125]:
min_count = int(((100-20)/100) *df.shape[0] + 1)

In [126]:
df = df.dropna(axis=1, thresh=min_count)

In [127]:

df.shape

(1445, 77)

In [128]:
# row_min_count = int(((5)/100) * df.shape[0] + 1)
df = df.dropna(thresh=len(df.columns)-1)
df.shape

(1207, 77)

In [129]:
print(row_min_count)
print(min_count)
print(len(df.columns)-1)

73
1157
76

In [130]:
#check null value 
df.isnull().sum()

Region                                      0
Name of County                              0
Name of Sub- County                         0
What is the school category                 0
What is the gender of the students?         0
                                           ..
Total enrolment of boarders                 0
Total Dormitory Floor area                  0
Temporary Dormitory                         0
Inadequate and overcrowded  dormitories     0
Total number of beds                        0
Length: 77, dtype: int64

In [131]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

     Region  ... Does the region experience any inter/intra community conflicts or attacks?
3  Region 1  ...                                                 No
4  Region 1  ...                                                 No
5  Region 1  ...                                                 No
6  Region 1  ...                                                Yes
7  Region 1  ...                                                Yes

[5 rows x 30 columns]

In [132]:
obj_df.dtypes

Region                                                                                                                               object
Name of County                                                                                                                       object
Name of Sub- County                                                                                                                  object
What is the school category                                                                                                          object
What is the gender of the students?                                                                                                  object
What form of accommodation does the school operate?                                                                                  object
Type of school                                                                                                                       object
Location of school                                                                                                                   object
Did the school receive any funding in the year 2017 or 2018?                                                                         object
Does the school have Dormitories?                                                                                                    object
Does the school have Smart Classrooms                                                                                                object
Does the school have ICT laboratories / Room?                                                                                        object
Does the school have a library?                                                                                                      object
What is the general condition of repair of the classrooms?                                                                           object
Does the school conduct classes in open air or under trees?                                                                          object
Does the school have toilets for students?                                                                                           object
What kind of toilets does the school have?                                                                                           object
Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (Bathing areas)                object
Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM materials (e.g. pads))    object
Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (MHM education)                object
Which of the following provisions for menstrual hygiene management (MHM) are available at the school? (None)                         object
Is the school connected to KLPC electricity?                                                                                         object
What kind of internet connection does the school have? (Fiber/structured cabling)                                                    object
What kind of internet connection does the school have? (Wireless Broadband/modem)                                                    object
What kind of internet connection does the school have? (Mobile phones)                                                               object
What kind of internet connection does the school have? (None)                                                                        object
Is noise from the surrounding environment a problem with the school?                                                                 object
Are there some health & safety challenges that may arise as a result of the infrastructural development in your schools?             object
Is the community prone to insecurity challenges?                                                                                     object
Does the region experience any inter/intra community conflicts or attacks?                                                           object
dtype: object

In [133]:
X = obj_df.iloc[:,:-1].values
X

array([['Region 1', 'Kakamega County', 'BUTERE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kakamega County', 'BUTERE SUB-COUNTY', ..., 'No',
        'Yes', 'Yes'],
       ['Region 1', 'West Pokot County', 'POKOT SOUTH SUB-COUNTY', ...,
        'No', 'No', 'No'],
       ...,
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No']], dtype=object)

In [134]:


from sklearn.preprocessing import LabelEncoder
lblencode = LabelEncoder()
X[:,0] = lblencode.fit_transform(X[:,:-1])
X

ValueError: ignored

In [112]:
# using sklearn-pandas package
from sklearn_pandas import CategoricalImputer
 
# handling NaN values
imputer = CategoricalImputer()
data = np.array(obj_df, dtype=object)
imputer.fit_transform(data)

array([['Region 1', 'Kakamega County', 'BUTERE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kakamega County', 'BUTERE SUB-COUNTY', ..., 'Yes',
        'Yes', 'No'],
       ['Region 1', 'West Pokot County', 'POKOT SOUTH SUB-COUNTY', ...,
        'No', 'No', 'No'],
       ...,
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No'],
       ['Region 1', 'Kisii County', 'NYAMACHE SUB-COUNTY', ..., 'No',
        'No', 'No']], dtype=object)

In [ ]:
data.isnull().sum()

AttributeError: ignored